site_name: Python 3
site_url: https://py3dev.ru/
site_description: Справочник Python-разработчика с примерами кода
site_author: py3dev.ru
copyright: (C) 2021-2023, Справочник python-разработчика с примерами кода

repo_name: 'Справочник на Github'
repo_url: 'https://github.com/xsltdev/py3dev.ru'

theme:
    name: material
    custom_dir: overrides
    palette:
        primary: indigo
        accent: indigo
    language: ru
    features:
        - navigation.tabs
        - navigation.tracking
        - navigation.instant
    favicon: python.svg
    logo: python.svg

extra:
    social:
        - icon: fontawesome/brands/html5
          link: 'https://hcdev.ru/'
          name: HTML and CSS docs
        - icon: fontawesome/brands/js
          link: 'https://scriptdev.ru/'
          name: Javascript
        - icon: fontawesome/brands/angular
          link: 'https://angdev.ru/'
          name: Angular docs
        - icon: fontawesome/brands/react
          link: 'https://reactdev.ru/'
          name: React docs
        - icon: fontawesome/brands/node-js
          link: 'https://nodejsdev.ru/'
          name: Node.js docs
        - icon: fontawesome/brands/python
          link: 'https://py3dev.ru/'
          name: Python 3 docs
        - icon: fontawesome/solid/code
          link: 'https://xsltdev.ru/'
          name: XSLT docs

#google_analytics:
#    - UA-34215161-1
#    - auto

markdown_extensions:
    - admonition
    - codehilite:
          guess_lang: false
          linenums: false
    - toc:
          permalink: true
    - pymdownx.extra
    - pymdownx.details
    - pymdownx.emoji:
          emoji_index: !!python/name:materialx.emoji.twemoji
          emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.tabbed
    - pymdownx.superfences

plugins:
    - search:
          separator: '[\s\-\:]+'
          lang:
              - ru
              - en
    - awesome-pages
    - section-index
    - social

extra_css:
    - '/assets/stylesheets/styles.css?2'
